image:
  repository: ghcr.io/stordco/sre-technical-challenge
  tag: latest

# Non-sensitive environment variables
env:
  DATABASE_URL: postgresql://postgres:password@sre-db-postgresql.stord.svc.cluster.local:5432/sre-technical-challenge
  PHX_HOST: localhost
  POOL_SIZE: 10
  PORT: 4000

# Sensitive environment variables (secrets)
secrets:
  SECRET_KEY_BASE: GWks+00R99rp4iCigXEDAP7WRQXFiTImOP0vIUmFyaNj1DGDXsMvEfSXtb7ITMKC

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /_health
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /_health
    initialDelaySeconds: 5
    periodSeconds: 5

containerSecurityContext:
  runAsUser: 1001
  fsGroup: 1001

primary:
  persistence:
    storageClass: "gp2"
  initContainers:
    - name: fix-permissions
      image: busybox
      command: ["sh", "-c", "chown -R 1001:1001 /bitnami/postgresql/data"]
      volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql/data

serviceAccount:
  create: true
  name: ""

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"