apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sre-app.fullname" . }}-config
  labels:
    {{- include "sre-app.labels" . | nindent 4 }}
data:
  # Non-sensitive environment variables from values.yaml
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  PHX_HOST: {{ .Values.env.PHX_HOST | quote }}
  POOL_SIZE: {{ .Values.env.POOL_SIZE | quote }}
  PORT: {{ .Values.env.PORT | quote }}