apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app-release-name
  labels:
    app: sre-app
    release: release-name
    chart: sre-app-0.1.0
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-app
      release: release-name
  template:
    metadata:
      labels:
        app: sre-app
        release: release-name
    spec:
      containers:
        - name: sre-app
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          image: "ghcr.io/stordco/sre-technical-challenge:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sre-app-release-name-config
            - secretRef:
                name: sre-app-release-name-secrets
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /_health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 1001
            fsGroup: 1001