# templates/migrate-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sre-app-sre-technical-challenge-migrate
  namespace: stord
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/stordco/sre-technical-challenge:latest
          command: ["./sre_technical_challenge", "eval", "Application.ensure_all_started(:sre_technical_challenge); Ecto.Migrator.run(SreTechnicalChallenge.Repo, :up, all: true)"]



          env:
            - name: DATABASE_URL
              value: postgresql://postgres:password@sre-db-postgresql.stord.svc.cluster.local:5432/sre-technical-challenge
            - name: PHX_HOST
              value: localhost
            - name: POOL_SIZE
              value: "10"
            - name: PORT
              value: "4000"
            - name: SECRET_KEY_BASE
              value: GWks+00R99rp4iCigXEDAP7WRQXFiTImOP0vIUmFyaNj1DGDXsMvEfSXtb7ITMKC
      restartPolicy: Never
  backoffLimit: 4