apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sre-app.fullname" . }}-secrets
  labels:
    {{- include "sre-app.labels" . | nindent 4 }}
stringData:
  # Sensitive environment variables from values.yaml
  SECRET_KEY_BASE: {{ .Values.env.SECRET_KEY_BASE | quote }}