apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-app.fullname" . }}
  labels:
    {{- include "sre-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.env.PORT }}
  selector:
    {{- include "sre-app.selectorLabels" . | nindent 4 }}